spring:
    datasource:
        password: password
        url: jdbc:h2:dev
        username: SA
    JDBCConnectionCount: 20
    application:
      name: prodcatalog

ConnectionCount: 30
WorkerThreadCount: 25
server:
  port: 6004
