spring:
    datasource:
        password: password
        url: jdbc:h2:dev
        username: SA
    JDBCConnectionCount: 21
    application:
      name: proddetail

ConnectionCount: 36
WorkerThreadCount: 30
server:
  port: 6004
