spring:
    datasource:
        password: password
        url: jdbc:h2:dev
        username: SA
    JDBCConnectionCount: 22
    application:
      name: prodcatalog

ConnectionCount: 21
WorkerThreadCount: 18
server:
  port: 6004
